services:
  hirenow:
    image: ghcr.io/buildprocure/hirenow:latest
    build:
      context: .
    container_name: hirenow
    restart: unless-stopped
    ports:
      - "3100:80"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    external: true
